name: Convert ASS to LRC

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'ass/**/*.ass'
  pull_request:
    paths:
      - 'ass/**/*.ass'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: task install
        
      - name: Lint lyrics
        run: task lint
        
      - name: Convert ASS to LRC
        run: task convert
        
      - name: Upload compiled lyrics
        uses: actions/upload-artifact@v4
        with:
          name: compiled-lyrics
          path: compiled/
          retention-days: 30
          
      - name: Commit and push compiled files
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add compiled/
          git diff --staged --quiet || git commit -m "chore: update compiled LRC files [skip ci]"
          git push
